### ISSUE TITLE
Media3

### ISSUE THREAD

**Issue by jakepurple13** [dsa28s/compose-video#1]
Any plans to upgrade to [Media3](https://developer.android.com/jetpack/androidx/releases/media3#1.0.0-beta03) from Exoplayer?

**Comment by dsa28s** [comment]
@jakepurple13 Of course there is. The `media3` package is still in beta, so when it is released as stable, i will migrate the library to media3 based accordingly.

**Comment by dsa28s** [comment]
@jakepurple13 Today, I published library version 1.2.0
Major update contains upgrade to Media3 from Exoplayer.

Thank you!

**Comment by itolianezzz** [comment]
@dsa28s Hello! Is it really published? Doesn't seem to appear in maven repository 🤷‍♂️ 
https://mvnrepository.com/artifact/io.sanghun/compose-video

**Comment by dsa28s** [comment]
@itolianezzz https://central.sonatype.com/artifact/io.sanghun/compose-video/1.2.0/versions
I checked yesterday, but 1.2.0 deployment is not correctly. So i tried 1.2.0 deploy at maven central, and currently available version 1.2.0!
