### ISSUE TITLE
M3U8 video not playing

### ISSUE THREAD

**Issue by itsallan** [dsa28s/compose-video#27]
i don't know if am doing anything wrong but  but m3u8 not playing let me attach my code
`                    var repeatMode by remember { mutableStateOf(RepeatMode.NONE) }
                    VideoPlayerCacheManager.initialize(context, 1024 * 1024 * 1024)
                    VideoPlayer(
                        mediaItems = listOf(
                            VideoPlayerMediaItem.NetworkMediaItem(
                                url = videoUrl,
                                mediaMetadata = MediaMetadata.Builder().setTitle(title).build(),
                                mimeType = MimeTypes.APPLICATION_M3U8,
                            )
                        ),
                        handleLifecycle = true,
                        autoPlay = true,
                        usePlayerController = true,
                        enablePip = true,
                        handleAudioFocus = true,
                        controllerConfig = VideoPlayerControllerConfig(
                            showSpeedAndPitchOverlay = true,
                            showSubtitleButton = true,
                            showCurrentTimeAndTotalTime = true,
                            showBufferingProgress = true,
                            showForwardIncrementButton = true,
                            showBackwardIncrementButton = true,
                            showBackTrackButton = false,
                            showNextTrackButton = false,
                            showRepeatModeButton = true,
                            controllerShowTimeMilliSeconds = 5_000,
                            controllerAutoShow = true,
                            showFullScreenButton = true,
                        ),
                        volume = 0.8f,  // volume 0.0f to 1.0f
                        repeatMode = RepeatMode.NONE,       // or RepeatMode.ALL, RepeatMode.ONE
                        onCurrentTimeChanged = { // long type, current player time (millisec)
                            Log.e("CurrentTime", it.toString())
                        },
                        playerInstance = {
                            android.util.Log.e("VOLUME", volume.toString())
                            addAnalyticsListener(object : AnalyticsListener {
                                @SuppressLint("UnsafeOptInUsageError")
                                override fun onRepeatModeChanged(
                                    eventTime: AnalyticsListener.EventTime,
                                    rMode: Int,
                                ) {
                                    repeatMode = rMode.toRepeatMode()

                                }

                                @SuppressLint("UnsafeOptInUsageError")
                                override fun onPlayWhenReadyChanged(
                                    eventTime: AnalyticsListener.EventTime,
                                    playWhenReady: Boolean,
                                    reason: Int,
                                ) {

                                }

                                @SuppressLint("UnsafeOptInUsageError")
                                override fun onVolumeChanged(
                                    eventTime: AnalyticsListener.EventTime,
                                    volume: Float,
                                ) {

                                }
                            })
                        },`
![photo_5978802000718054152_y](https://github.com/dsa28s/compose-video/assets/134838992/7131a621-f6f8-4e86-988a-32a666e6e2b7)

**Comment by dsa28s** [comment]
@itsallan Hello! Please upgrade androidx.media3 package version to latest version? I think this issue is related to exoplayer engine.

**Comment by itsallan** [comment]
@dsa28s  check this 
![media player dp](https://github.com/dsa28s/compose-video/assets/134838992/229532b5-2de9-4b5f-a2a1-70eadc6c744b)

**Comment by dsa28s** [comment]
@itsallan  Is it the same if update it to 1.3.1??

**Comment by itsallan** [comment]
@dsa28s I have managed to fix it but it's plays like 1 minute and it pauses, so I just shifted to the original Media3 API because it doesn't pause
